// ─── Lightweight spell corrector ─────────────────────────────────────────────
// Corrects common typos in user input before it reaches the model.
// Strategy: curated high-precision typo map first, then fuzzy Levenshtein
// correction against a common-word dictionary (edit distance <= 2).

// ─── High-precision common typo map ───────────────────────────────────────────
// Exact-word replacements for the most frequent typing mistakes.
const TYPO_MAP: Record<string, string> = {
  'teh': 'the',
  'recieve': 'receive',
  'recieved': 'received',
  'definately': 'definitely',
  'seperate': 'separate',
  'occured': 'occurred',
  'untill': 'until',
  'becuase': 'because',
  'becaus': 'because',
  'bcuz': 'because',
  'becasue': 'because',
  'whts': 'whats',
  'wht': 'what',
  'wat': 'what',
  'wut': 'what',
  'wat is': 'what is',
  'hw': 'how',
  'hwo': 'how',
  'hw r': 'how are',
  'r u': 'are you',
  'ur': 'your',
  'u r': 'you are',
  'u': 'you',
  'yo': 'you',
  'yuo': 'you',
  'pls': 'please',
  'plz': 'please',
  'plse': 'please',
  'thx': 'thanks',
  'thanx': 'thanks',
  'tnx': 'thanks',
  'tysm': 'thank you so much',
  'thnks': 'thanks',
  'ok': 'okay',
  'k': 'okay',
  'kk': 'okay',
  'btw': 'by the way',
  'idk': 'i do not know',
  'dunno': 'do not know',
  'tbh': 'to be honest',
  'imo': 'in my opinion',
  'imho': 'in my humble opinion',
  'asap': 'as soon as possible',
  'u know': 'you know',
  'gonna': 'going to',
  'wanna': 'want to',
  'gotta': 'got to',
  'lemme': 'let me',
  'gimme': 'give me',
  'dont': 'do not',
  'doesnt': 'does not',
  'didnt': 'did not',
  'isnt': 'is not',
  'arent': 'are not',
  'wont': 'will not',
  'cant': 'cannot',
  'couldnt': 'could not',
  'shouldnt': 'should not',
  'wouldnt': 'would not',
  'havent': 'have not',
  'hasnt': 'has not',
  'wasnt': 'was not',
  'werent': 'were not',
  'its': "it's",
  'thats': "that's",
  'whats': "what's",
  'how is': 'how is',
  'thers': "there's",
  'im': "I'm",
  'ive': "I've",
  'id': "I'd",
  'ill': "I'll",
  'youre': "you're",
  'weve': "we've",
  'theyre': "they're",
  'its not': "it's not",
  'helo': 'hello',
  'hii': 'hi',
  'hiii': 'hi',
  'helloo': 'hello',
  'hellow': 'hello',
  'hola': 'hello',
  'hay': 'hey',
  'heyy': 'hey',
  'wat up': 'what up',
  'buid': 'build',
  'creat': 'create',
  'funtion': 'function',
  'funktion': 'function',
  'funciton': 'function',
  'fucntion': 'function',
  'variabe': 'variable',
  'variabel': 'variable',
  'eror': 'error',
  'erorrs': 'errors',
  'erros': 'errors',
  'debbug': 'debug',
  'debuge': 'debug',
  'deebug': 'debug',
  'compil': 'compile',
  'comile': 'compile',
  'compilaton': 'compilation',
  'messsage': 'message',
  'messge': 'message',
  'mesage': 'message',
  'massege': 'message',
  'mesagee': 'message',
  'massage': 'message',
  'buton': 'button',
  'butto': 'button',
  'fils': 'files',
  'flie': 'file',
  'floder': 'folder',
  'fodler': 'folder',
  'dowload': 'download',
  'downlod': 'download',
  'downlaod': 'download',
  'upoad': 'upload',
  'upoload': 'upload',
  'serach': 'search',
  'sarch': 'search',
  'seach': 'search',
  'seacrh': 'search',
  'seeting': 'setting',
  'seting': 'setting',
  'setings': 'settings',
  'confg': 'config',
  'configuraton': 'configuration',
  'exmaple': 'example',
  'exaple': 'example',
  'exmple': 'example',
  'explaination': 'explanation',
  'explination': 'explanation',
  'exlain': 'explain',
  'explane': 'explain',
  'soltion': 'solution',
  'sollution': 'solution',
  'soluton': 'solution',
  'prblem': 'problem',
  'probem': 'problem',
  'porblem': 'problem',
  'queston': 'question',
  'qestion': 'question',
  'qustion': 'question',
  'answe': 'answer',
  'ansr': 'answer',
  'anwser': 'answer',
  'wheter': 'weather',
  'wether': 'weather',
  'weater': 'weather',
  'temprature': 'temperature',
  'tempature': 'temperature',
  'beautifull': 'beautiful',
  'beutiful': 'beautiful',
  'differnt': 'different',
  'diferent': 'different',
  'alwys': 'always',
  'alwyas': 'always',
  'becme': 'become',
  'befor': 'before',
  'begginer': 'beginner',
  'begining': 'beginning',
  'beleive': 'believe',
  'belive': 'believe',
  'businesss': 'business',
  'calender': 'calendar',
  'carier': 'career',
  'catagory': 'category',
  'completly': 'completely',
  'developement': 'development',
  'enviroment': 'environment',
  'enviornment': 'environment',
  'exersise': 'exercise',
  'experiance': 'experience',
  'exprience': 'experience',
  'frequenty': 'frequently',
  'freind': 'friend',
  'friendlyy': 'friendly',
  'goverment': 'government',
  'graet': 'great',
  'grate': 'great',
  'happend': 'happened',
  'happyness': 'happiness',
  'hellp': 'help',
  'hlep': 'help',
  'hackathon': 'hackathon',
  'interuption': 'interruption',
  'knowlege': 'knowledge',
  'knowledg': 'knowledge',
  'languge': 'language',
  'langauge': 'language',
  'littel': 'little',
  'maintenence': 'maintenance',
  'neccessary': 'necessary',
  'neccesary': 'necessary',
  'occassion': 'occasion',
  'perfomance': 'performance',
  'perfromance': 'performance',
  'posible': 'possible',
  'posisble': 'possible',
  'prefrence': 'preference',
  'psycology': 'psychology',
  'remeber': 'remember',
  'rememeber': 'remember',
  'responce': 'response',
  'responsiblity': 'responsibility',
  'resturant': 'restaurant',
  'sepreate': 'separate',
  'succesful': 'successful',
  'sucessful': 'successful',
  'successfull': 'successful',
  'suprise': 'surprise',
  'sytem': 'system',
  'tommorow': 'tomorrow',
  'tomorow': 'tomorrow',
  'truely': 'truly',
  'vacum': 'vacuum',
  'writting': 'writing',
  'wierd': 'weird',
  'wich': 'which',
  'whith': 'with',
  'wroking': 'working',
  'workng': 'working',
  'workig': 'working',
  'woriking': 'working',
  'yesterdayy': 'yesterday',
  'accross': 'across',
  'adress': 'address',
  'appriciate': 'appreciate',
  'arround': 'around',
  'articel': 'article',
  'asign': 'assign',
  'asychronous': 'asynchronous',
  'auther': 'author',
  'awlays': 'always',
  'cahnce': 'chance',
  'challange': 'challenge',
  'chceck': 'check',
  'chose': 'choose',
  'ckech': 'check',
  'colur': 'color',
  'compnent': 'component',
  'contet': 'content',
  'corret': 'correct',
  'criteriaa': 'criteria',
  'cuz': 'because',
  'dats': 'that',
  'daya': 'data',
  'decideing': 'deciding',
  'descision': 'decision',
  'determin': 'determine',
  'diifrent': 'different',
  'dont now': 'do not know',
  'douwn': 'down',
  'eigth': 'eight',
  'engin': 'engine',
  'equaly': 'equally',
  'evenn': 'even',
  'everthing': 'everything',
  'everyhting': 'everything',
  'expresion': 'expression',
  'facilityy': 'facility',
  'faily': 'family',
  'finnaly': 'finally',
  'finall': 'final',
  'forty': 'fourty',
  'foward': 'forward',
  'funtions': 'functions',
  'gerneral': 'general',
  'gorgeous': 'gorgeous',
  'grpah': 'graph',
  'guardian': 'guardian',
  'happenn': 'happen',
  'hast': 'has',
  'hav': 'have',
  'hepl': 'help',
  'herseelf': 'herself',
  'higest': 'highest',
  'hiself': 'himself',
  'hopefull': 'hopefully',
  'how to': 'how to',
  'humor': 'humor',
  'hy': 'hey',
  'includ': 'include',
  'inculde': 'include',
  'indetified': 'identified',
  'informaiton': 'information',
  'infromation': 'information',
  'integraion': 'integration',
  'interger': 'integer',
  'itn': 'it',
  'knowkedge': 'knowledge',
  'libary': 'library',
  'lis': 'list',
  'listenning': 'listening',
  'logicly': 'logically',
  'loopng': 'looping',
  'machie': 'machine',
  'managment': 'management',
  'mearn': 'mean',
  'measurement': 'measurement',
  'meduim': 'medium',
  'meesage': 'message',
  'methodologyy': 'methodology',
  'mightt': 'might',
  'modles': 'models',
  'mulitple': 'multiple',
  'multipe': 'multiple',
  'natrual': 'natural',
  'negitive': 'negative',
  'notifcations': 'notifications',
  'nubmer': 'number',
  'numberical': 'numerical',
  'oppurtunity': 'opportunity',
  'originaly': 'originally',
  'overiew': 'overview',
  'paralell': 'parallel',
  'patern': 'pattern',
  'perfom': 'perform',
  'permisson': 'permission',
  'placment': 'placement',
  'popluation': 'population',
  'possibilties': 'possibilities',
  'precisley': 'precisely',
  'preffered': 'preferred',
  'presentationn': 'presentation',
  'procedd': 'proceed',
  'programm': 'program',
  'proprty': 'property',
  'propery': 'property',
  'protocal': 'protocol',
  'psuedo': 'pseudo',
  'publically': 'publicly',
  'pursue': 'pursue',
  'randomly': 'randomly',
  'reccommend': 'recommend',
  'recomend': 'recommend',
  'recursionn': 'recursion',
  'refernce': 'reference',
  'regualr': 'regular',
  'releated': 'related',
  'relevent': 'relevant',
  'rendere': 'render',
  'reponsive': 'responsive',
  'repositiory': 'repository',
  'reslover': 'resolver',
  'resourse': 'resource',
  'responive': 'responsive',
  'resut': 'result',
  'retrun': 'return',
  'reveiw': 'review',
  'runnig': 'running',
  'sciencs': 'science',
  'secound': 'second',
  'selecton': 'selection',
  'sencors': 'sensors',
  'sentance': 'sentence',
  'sentene': 'sentence',
  'sequece': 'sequence',
  'shcedule': 'schedule',
  'simillar': 'similar',
  'similary': 'similarly',
  'simliar': 'similar',
  'slect': 'select',
  'sollve': 'solve',
  'somethign': 'something',
  'somthing': 'something',
  'specail': 'special',
  'specifc': 'specific',
  'sppeeds': 'speeds',
  'stae': 'state',
  'strat': 'start',
  'strenght': 'strength',
  'stucture': 'structure',
  'succeful': 'successful',
  'sumarize': 'summarize',
  'suppport': 'support',
  'suprisingly': 'surprisingly',
  'sutiable': 'suitable',
  'sycronization': 'synchronization',
  'tahnks': 'thanks',
  'testng': 'testing',
  'thier': 'their',
  'thign': 'thing',
  'thik': 'think',
  'thikn': 'think',
  'thisn': 'this',
  'thorugh': 'through',
  'thre': 'three',
  'thsi': 'this',
  'toogle': 'toggle',
  'togle': 'toggle',
  'tranistion': 'transition',
  'trasfer': 'transfer',
  'triggerd': 'triggered',
  'ture': 'true',
  'unlke': 'unlike',
  'updtate': 'update',
  'upldate': 'update',
  'usefull': 'useful',
  'usernames': 'username',
  'utlities': 'utilities',
  'varible': 'variable',
  'veriable': 'variable',
  'versin': 'version',
  'waht': 'what',
  'welll': 'well',
  'wen': 'when',
  'wher': 'where',
  'wihch': 'which',
  'wiht': 'with',
  'wokring': 'working',
  'writeen': 'written',
  'wtih': 'with',
  'yeahh': 'yeah',
  'aboutt': 'about',
  'abovee': 'above',
  'afterr': 'after',
  'againn': 'again',
  'agaisnt': 'against',
  'allw': 'all',
  'allways': 'always',
  'alsot': 'also',
  'amoung': 'among',
  'andal': 'and',
  'anie': 'any',
  'anothe': 'another',
  'aslo': 'also',
  'ato': 'at',
  'bact': 'back',
  'basicaly': 'basically',
  'befroe': 'before',
  'beleve': 'believe',
  'cahnges': 'changes',
  'chcek': 'check',
  'closs': 'close',
  'cmae': 'came',
  'coud': 'could',
  'coukd': 'could',
  'datails': 'details',
  'deatil': 'detail',
  'developr': 'developer',
  'didntt': 'did not',
  'differnet': 'different',
  'diffrent': 'different',
  'direcotry': 'directory',
  'direcctory': 'directory',
  'dont understand': 'do not understand',
  'enabel': 'enable',
  'ensur': 'ensure',
  'evrey': 'every',
  'explaain': 'explain',
  'exterme': 'extreme',
  'finsih': 'finish',
  'firset': 'first',
  'folow': 'follow',
  'folowing': 'following',
  'forbidden': 'forbidden',
  'freame': 'frame',
  'fucntionality': 'functionality',
  'functuion': 'function',
  'grabage': 'garbage',
  'happendd': 'happened',
  'harware': 'hardware',
  'hepler': 'helper',
  'howevr': 'however',
  'implmentation': 'implementation',
  'implment': 'implement',
  'inbetween': 'between',
  'indentifier': 'identifier',
  'inital': 'initial',
  'inmport': 'import',
  'instalation': 'installation',
  'intall': 'install',
  'interace': 'interface',
  'itsefl': 'itself',
  'laser': 'laser',
  'limted': 'limited',
  'liste': 'list',
  'loook': 'look',
  'maxmimum': 'maximum',
  'meaningfull': 'meaningful',
  'memeber': 'member',
  'mena': 'mean',
  'mens': 'means',
  'minmun': 'minimum',
  'mistke': 'mistake',
  'modul': 'module',
  'mroe': 'more',
  'mutiple': 'multiple',
  'notic': 'notice',
  'notifcation': 'notification',
  'nubmers': 'numbers',
  'occurr': 'occur',
  'oppositee': 'opposite',
  'optmization': 'optimization',
  'optomization': 'optimization',
  'otherr': 'other',
  'ouput': 'output',
  'outptu': 'output',
  'owrking': 'working',
  'particulary': 'particularly',
  'paramater': 'parameter',
  'paramter': 'parameter',
  'partt': 'part',
  'paylod': 'payload',
  'peice': 'piece',
  'perharps': 'perhaps',
  'perhpas': 'perhaps',
  'prety': 'pretty',
  'probabaly': 'probably',
  'probablt': 'probably',
  'probally': 'probably',
  'procude': 'produce',
  'producy': 'product',
  'profie': 'profile',
  'progarm': 'program',
  'progrma': 'program',
  'promiss': 'promise',
  'puting': 'putting',
  'ractangle': 'rectangle',
  'realy': 'really',
  'realyl': 'really',
  'reccomendation': 'recommendation',
  'receivee': 'receive',
  'refered': 'referred',
  'regulary': 'regularly',
  'reloadd': 'reload',
  'renader': 'render',
  'represet': 'represent',
  'requird': 'required',
  'requsted': 'requested',
  'respositories': 'repositories',
  'rwite': 'write',
  'scoend': 'second',
  'sence': 'sense',
  'shoudl': 'should',
  'shuld': 'should',
  'simultaneusly': 'simultaneously',
  'situationn': 'situation',
  'smoothy': 'smoothly',
  'soemthing': 'something',
  'sourcce': 'source',
  'spcefic': 'specific',
  'specfiic': 'specific',
  'srting': 'string',
  'stuctures': 'structures',
  'sucsess': 'success',
  'sumamry': 'summary',
  'supress': 'suppress',
  'swicth': 'switch',
  'techology': 'technology',
  'tehnology': 'technology',
  'temperautre': 'temperature',
  'terminologyy': 'terminology',
  'threhold': 'threshold',
  'togheter': 'together',
  'tonigh': 'tonight',
  'transsaction': 'transaction',
  'truy': 'truly',
  'understnad': 'understand',
  'understan': 'understand',
  'unde': 'under',
  'usef': 'use',
  'vairous': 'various',
  'verison': 'version',
  'wats': "what's",
  'wahts': "what's",
  'wehn': 'when',
  'whta': 'what',
  'widsget': 'widget',
  'willl': 'will',
  'woith': 'with',
  'workload': 'workload',
  'wouldd': 'would',
  'writte': 'write',
  'yearly': 'yearly',
  'yuor': 'your',
  'yourselves': 'yourselves',
};

// ─── Common word dictionary (frequency-ish ordered) ────────────────────────────
const COMMON_WORDS: string[] = [
  'the', 'and', 'that', 'have', 'for', 'not', 'with', 'you', 'this', 'but', 'his',
  'are', 'from', 'they', 'say', 'she', 'her', 'will', 'one', 'all', 'would', 'there',
  'their', 'what', 'about', 'which', 'when', 'make', 'can', 'like', 'time', 'just',
  'him', 'know', 'take', 'people', 'into', 'year', 'your', 'good', 'some', 'could',
  'them', 'see', 'other', 'than', 'then', 'now', 'look', 'only', 'come', 'its',
  'over', 'think', 'also', 'back', 'after', 'use', 'two', 'how', 'our', 'work',
  'first', 'well', 'way', 'even', 'new', 'want', 'because', 'any', 'these', 'give',
  'day', 'most', 'help', 'thing', 'many', 'being', 'through', 'much', 'before',
  'right', 'too', 'mean', 'live', 'where', 'little', 'round', 'man', 'came',
  'show', 'every', 'me', 'under', 'name', 'very', 'form', 'sentence', 'great',
  'low', 'line', 'differ', 'turn', 'cause', 'move', 'boy', 'old', 'same', 'tell',
  'does', 'set', 'three', 'air', 'play', 'small', 'end', 'put', 'home', 'read',
  'hand', 'port', 'large', 'spell', 'add', 'land', 'here', 'must', 'big', 'high',
  'such', 'follow', 'act', 'why', 'ask', 'men', 'change', 'went', 'light', 'kind',
  'off', 'need', 'house', 'picture', 'try', 'again', 'animal', 'point', 'mother',
  'world', 'near', 'build', 'self', 'earth', 'father', 'head', 'stand', 'own',
  'page', 'should', 'country', 'found', 'answer', 'school', 'grow', 'study',
  'still', 'learn', 'plant', 'cover', 'food', 'sun', 'four', 'between', 'state',
  'keep', 'eye', 'never', 'last', 'let', 'thought', 'city', 'tree', 'cross',
  'farm', 'hard', 'start', 'might', 'story', 'saw', 'far', 'sea', 'draw', 'left',
  'late', 'run', 'while', 'press', 'close', 'night', 'real', 'life', 'few',
  'north', 'open', 'seem', 'together', 'next', 'white', 'children', 'begin',
  'got', 'walk', 'example', 'ease', 'paper', 'group', 'always', 'music', 'those',
  'both', 'mark', 'often', 'letter', 'until', 'mile', 'river', 'car', 'feet',
  'care', 'second', 'book', 'carry', 'took', 'science', 'eat', 'room', 'friend',
  'began', 'idea', 'fish', 'mountain', 'stop', 'once', 'base', 'hear', 'horse',
  'cut', 'sure', 'watch', 'color', 'face', 'wood', 'main', 'enough', 'plain',
  'girl', 'usual', 'young', 'ready', 'above', 'ever', 'red', 'list', 'though',
  'feel', 'talk', 'bird', 'soon', 'body', 'dog', 'family', 'direct', 'pose',
  'leave', 'song', 'measure', 'door', 'product', 'black', 'short', 'numeral',
  'class', 'wind', 'question', 'happen', 'complete', 'ship', 'area', 'half',
  'rock', 'order', 'fire', 'south', 'problem', 'piece', 'told', 'knew', 'pass',
  'since', 'top', 'whole', 'king', 'space', 'heard', 'best', 'hour', 'better',
  'true', 'during', 'hundred', 'five', 'remember', 'step', 'early', 'hold',
  'west', 'ground', 'interest', 'reach', 'fast', 'verb', 'sing', 'listen', 'six',
  'table', 'travel', 'less', 'morning', 'ten', 'simple', 'several', 'vowel',
  'toward', 'war', 'lay', 'against', 'pattern', 'slow', 'center', 'love',
  'person', 'money', 'serve', 'appear', 'road', 'map', 'rain', 'rule', 'govern',
  'pull', 'cold', 'notice', 'voice', 'unit', 'power', 'town', 'fine', 'certain',
  'fly', 'fall', 'lead', 'cry', 'dark', 'machine', 'note', 'wait', 'plan',
  'figure', 'star', 'box', 'noun', 'field', 'rest', 'correct', 'able', 'pound',
  'done', 'beauty', 'drive', 'stood', 'contain', 'front', 'teach', 'week',
  'final', 'gave', 'green', 'oh', 'quick', 'develop', 'ocean', 'warm', 'free',
  'minute', 'strong', 'special', 'mind', 'behind', 'clear', 'tail', 'produce',
  'fact', 'street', 'inch', 'multiply', 'nothing', 'course', 'stay', 'wheel',
  'full', 'force', 'blue', 'object', 'decide', 'surface', 'deep', 'moon',
  'island', 'foot', 'system', 'busy', 'test', 'record', 'boat', 'common', 'gold',
  'possible', 'plane', 'stead', 'dry', 'wonder', 'laugh', 'thousand', 'ago',
  'ran', 'check', 'game', 'shape', 'equate', 'hot', 'miss', 'brought', 'heat',
  'snow', 'tire', 'bring', 'yes', 'distant', 'fill', 'east', 'paint', 'language',
  'among', 'grand', 'ball', 'yet', 'wave', 'drop', 'heart', 'am', 'present',
  'heavy', 'dance', 'engine', 'position', 'arm', 'wide', 'sail', 'material',
  'size', 'vary', 'settle', 'speak', 'weight', 'general', 'ice', 'matter',
  'circle', 'pair', 'include', 'divide', 'syllable', 'felt', 'perhaps', 'pick',
  'sudden', 'count', 'square', 'reason', 'length', 'represent', 'art', 'subject',
  'region', 'energy', 'hunt', 'probable', 'bed', 'brother', 'egg', 'ride', 'cell',
  'believe', 'fraction', 'forest', 'sit', 'race', 'window', 'store', 'summer',
  'train', 'sleep', 'prove', 'lone', 'leg', 'exercise', 'wall', 'catch', 'mount',
  'wish', 'sky', 'board', 'joy', 'winter', 'sat', 'written', 'wild', 'instrument',
  'kept', 'glass', 'grass', 'cow', 'job', 'edge', 'sign', 'visit', 'past',
  'soft', 'fun', 'bright', 'gas', 'weather', 'month', 'million', 'bear', 'finish',
  'happy', 'hope', 'flower', 'clothe', 'strange', 'gone', 'jump', 'baby', 'eight',
  'village', 'meet', 'root', 'buy', 'raise', 'solve', 'metal', 'whether', 'push',
  'seven', 'paragraph', 'third', 'shall', 'held', 'hair', 'describe', 'cook',
  'floor', 'either', 'result', 'burn', 'hill', 'safe', 'cat', 'century',
  'consider', 'type', 'law', 'bit', 'coast', 'copy', 'phrase', 'silent', 'tall',
  'sand', 'soil', 'roll', 'temperature', 'finger', 'industry', 'value', 'fight',
  'lie', 'beat', 'excite', 'natural', 'view', 'sense', 'ear', 'else', 'quite',
  'broke', 'case', 'middle', 'kill', 'son', 'lake', 'moment', 'scale', 'loud',
  'spring', 'observe', 'child', 'straight', 'consonant', 'nation', 'dictionary',
  'milk', 'speed', 'method', 'organ', 'pay', 'age', 'section', 'dress', 'cloud',
  'surprise', 'quiet', 'stone', 'tiny', 'climb', 'cool', 'design', 'poor', 'lot',
  'experiment', 'bottom', 'key', 'iron', 'single', 'stick', 'flat', 'twenty',
  'skin', 'smile', 'crease', 'hole', 'trade', 'melody', 'trip', 'office',
  'receive', 'row', 'mouth', 'exact', 'symbol', 'die', 'least', 'trouble',
  'shout', 'except', 'wrote', 'seed', 'tone', 'join', 'suggest', 'clean',
  'break', 'lady', 'yard', 'rise', 'bad', 'blow', 'oil', 'blood', 'touch',
  'grew', 'cent', 'mix', 'team', 'wire', 'cost', 'lost', 'brown', 'wear',
  'garden', 'equal', 'sent', 'choose', 'fell', 'fit', 'flow', 'fair', 'bank',
  'collect', 'save', 'control', 'decimal', 'gentle', 'woman', 'captain',
  'practice', 'separate', 'difficult', 'doctor', 'please', 'protect', 'noon',
  'whose', 'locate', 'ring', 'character', 'insect', 'caught', 'period',
  'indicate', 'radio', 'spoke', 'atom', 'human', 'history', 'effect', 'electric',
  'expect', 'crop', 'modern', 'element', 'hit', 'student', 'corner', 'party',
  'supply', 'bone', 'rail', 'imagine', 'provide', 'agree', 'thus', 'capital',
  'chair', 'danger', 'fruit', 'rich', 'thick', 'soldier', 'process', 'operate',
  'guess', 'necessary', 'sharp', 'wing', 'create', 'neighbor', 'wash', 'bat',
  'rather', 'crowd', 'corn', 'compare', 'poem', 'string', 'bell', 'depend',
  'meat', 'rub', 'tube', 'famous', 'dollar', 'stream', 'fear', 'sight', 'thin',
  'triangle', 'planet', 'hurry', 'chief', 'colony', 'clock', 'mine', 'tie',
  'enter', 'major', 'fresh', 'search', 'send', 'yellow', 'gun', 'allow', 'print',
  'dead', 'spot', 'desert', 'suit', 'current', 'lift', 'rose', 'continue',
  'block', 'chart', 'hat', 'sell', 'success', 'company', 'subtract', 'event',
  'particular', 'deal', 'swim', 'term', 'opposite', 'wife', 'shoe', 'shoulder',
  'spread', 'arrange', 'camp', 'invent', 'cotton', 'born', 'determine', 'quart',
  'nine', 'truck', 'noise', 'level', 'chance', 'gather', 'shop', 'stretch',
  'throw', 'shine', 'property', 'column', 'molecule', 'select', 'wrong', 'gray',
  'repeat', 'require', 'broad', 'prepare', 'salt', 'nose', 'plural', 'anger',
  'claim', 'continent', 'oxygen', 'sugar', 'death', 'pretty', 'skill', 'women',
  'season', 'solution', 'magnet', 'silver', 'thank', 'branch', 'match', 'suffix',
  'especially', 'fig', 'afraid', 'huge', 'sister', 'steel', 'discuss', 'forward',
  'similar', 'guide', 'experience', 'score', 'apple', 'bought', 'led', 'pitch',
  'coat', 'mass', 'card', 'band', 'rope', 'slip', 'win', 'dream', 'evening',
  'condition', 'feed', 'tool', 'total', 'basic', 'smell', 'valley', 'nor',
  'double', 'seat', 'arrive', 'master', 'track', 'parent', 'shore', 'division',
  'sheet', 'substance', 'favor', 'connect', 'post', 'spend', 'chord', 'fat',
  'glad', 'original', 'share', 'station', 'dad', 'bread', 'charge', 'proper',
  'bar', 'offer', 'segment', 'slave', 'duck', 'instant', 'market', 'degree',
  'populate', 'chick', 'dear', 'enemy', 'reply', 'drink', 'occur', 'support',
  'speech', 'nature', 'range', 'steam', 'motion', 'path', 'liquid', 'log',
  'meant', 'quotient', 'teeth', 'shell', 'neck', 'broken', 'today', 'hello',
  'really', 'people', 'something', 'things', 'going', 'coming', 'getting',
  'making', 'taking', 'looking', 'working', 'playing', 'using', 'coding', 'programming',
  'nice', 'write', 'wrote', 'written', 'fox', 'france', 'brown', 'quick', 'jumps',
  'lazy', 'dog', 'give', 'gave', 'given', 'maybe', 'might', 'probably',
  'would', 'could', 'should', 'must', 'can', 'cannot', 'used', 'use', 'using',
  'calls', 'call', 'need', 'needs', 'needed', 'like', 'likes', 'liked',
  'know', 'knows', 'known', 'think', 'thinks', 'thought', 'want', 'wants', 'wanted',
  'come', 'comes', 'came', 'going', 'went', 'gone', 'seen', 'saw', 'looking',
  'make', 'makes', 'made', 'work', 'works', 'worked', 'answer', 'answers',
  // Programming & tech terms
  'code', 'program', 'software', 'hardware', 'function', 'variable', 'array',
  'object', 'class', 'method', 'string', 'number', 'boolean', 'integer', 'float',
  'loop', 'while', 'return', 'import', 'export', 'default', 'const', 'let', 'var',
  'null', 'undefined', 'true', 'false', 'async', 'await', 'promise', 'callback',
  'event', 'click', 'button', 'input', 'output', 'error', 'debug', 'bug', 'fix',
  'build', 'run', 'compile', 'test', 'api', 'data', 'database', 'server', 'client',
  'frontend', 'backend', 'web', 'website', 'browser', 'html', 'css', 'javascript',
  'typescript', 'python', 'java', 'react', 'next', 'node', 'npm', 'git', 'github',
  'json', 'sql', 'app', 'application', 'file', 'folder', 'image', 'video', 'audio',
  'text', 'download', 'upload', 'link', 'url', 'email', 'password', 'user',
  'login', 'signup', 'register', 'google', 'account', 'profile', 'settings',
  'config', 'configuration', 'model', 'chat', 'bot', 'assistant', 'response',
  'question', 'answer', 'explain', 'example', 'solution', 'problem', 'issue',
  'feature', 'design', 'interface', 'responsive', 'mobile', 'desktop', 'call',
  'calling', 'based', 'using', 'works', 'working', 'created', 'lokesh',
  'verse', 'ai', 'github', 'context', 'project', 'source', 'state', 'props',
  'component', 'render', 'effect', 'hook', 'state', 'store', 'query', 'request',
  'response', 'header', 'body', 'status', 'route', 'middleware', 'deploy', 'host',
  'domain', 'secure', 'token', 'session', 'cookie', 'auth', 'security', 'error',
  'success', 'loading', 'empty', 'ready', 'started', 'done', 'complete', 'correct',
  'incorrect', 'invalid', 'valid', 'logical', 'practice', 'production', 'stage',
  'branch', 'commit', 'merge', 'pull', 'push', 'clone', 'repo', 'report',
];

const ALLOW_LIST = new Set([
  'ai', 'verse', 'lokesh', 'lucide', 'geist', 'supabase', 'vercel', 'tailwind',
  'nextjs', 'reactjs', 'nodejs', 'pdf', 'docx', 'csv', 'txt', 'url', 'api',
  'jsx', 'tsx', 'css', 'html', 'npm', 'yarn', 'pnpm', 'json', 'sql', 'sass',
  'scss', 'git', 'ios', 'android', 'web', 'ui', 'ux',
]);

const DICT_SET = new Set(COMMON_WORDS);

// ─── Levenshtein distance ─────────────────────────────────────────────────────
function levenshtein(a: string, b: string): number {
  const m = a.length;
  const n = b.length;
  if (m === 0) return n;
  if (n === 0) return m;
  const dp: number[] = Array.from({ length: n + 1 }, (_, i) => i);
  for (let i = 1; i <= m; i++) {
    let prev = dp[0];
    dp[0] = i;
    for (let j = 1; j <= n; j++) {
      const temp = dp[j];
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      dp[j] = Math.min(dp[j] + 1, dp[j - 1] + 1, prev + cost);
      prev = temp;
    }
  }
  return dp[n];
}

// ─── Fuzzy suggestion ─────────────────────────────────────────────────────────
// Returns best dictionary match within edit distance 2, preferring common words
// (earlier in list) and similar length.
function findSuggestion(word: string): string | null {
  const lower = word.toLowerCase();
  let best: string | null = null;
  let bestDist = 3;
  let bestLen = Infinity;
  let bestIdx = Infinity;

  for (let i = 0; i < COMMON_WORDS.length; i++) {
    const candidate = COMMON_WORDS[i];
    const dist = levenshtein(lower, candidate);
    if (dist > 2) continue;
    const lenDiff = Math.abs(candidate.length - lower.length);

    // Tier 1: smallest edit distance
    if (dist < bestDist) {
      bestDist = dist;
      bestLen = lenDiff;
      bestIdx = i;
      best = candidate;
    } else if (dist === bestDist) {
      // Tier 2: same distance → prefer closer length
      if (lenDiff < bestLen) {
        bestLen = lenDiff;
        bestIdx = i;
        best = candidate;
      } else if (lenDiff === bestLen) {
        // Tier 3: prefer more common (earlier index)
        if (i < bestIdx) {
          bestIdx = i;
          best = candidate;
        }
      }
    }
  }

  return best;
}

export interface CorrectionResult {
  original: string;
  corrected: string;
  changed: boolean;
  corrections: { from: string; to: string }[];
}

// Split message into words while tracking code blocks / URLs to skip
function shouldSkipContext(word: string, input: string, index: number): boolean {
  // Skip words inside backtick code spans
  const before = input.slice(0, index);
  const after = input.slice(index + word.length);
  const backtickCountBefore = (before.match(/`/g) || []).length;
  const backtickCountAfter = (after.match(/`/g) || []).length;
  if (backtickCountBefore % 2 === 1 || backtickCountAfter % 2 === 1) return true;

  // Skip URLs, emails, file paths, camelCase, and code-like tokens
  if (/(https?:\/\/|www\.|\.com|\.org|\.net|\.io|\.dev|\.app|\.py|\.ts|\.js|\.tsx|\.jsx|\.css|\.json|\.md\b)/.test(word)) return true;
  if (/@/.test(word)) return true;
  if (word.includes('_') || word.includes('-')) return true;
  if (/([a-z][A-Z])/.test(word)) return true; // camelCase
  return false;
}

// Correct spelling in a message
export function correctText(input: string): CorrectionResult {
  const corrections: { from: string; to: string }[] = [];

  const corrected = input.replace(/[A-Za-z]+/g, (word, index) => {
    const skip = shouldSkipContext(word, input, index);
    const lower = word.toLowerCase();

    // 1. Curated typo map (highest precision)
    if (!skip && TYPO_MAP[lower] && TYPO_MAP[lower] !== lower) {
      const to = TYPO_MAP[lower];
      const replacement = /^[A-Z]/.test(word)
        ? to.charAt(0).toUpperCase() + to.slice(1)
        : to;
      corrections.push({ from: word, to: replacement });
      return replacement;
    }

    // 2. Fuzzy correction
    const isAllCaps = word === word.toUpperCase() && word.length > 1;
    const hasDigit = /\d/.test(word);
    // Proper noun heuristic: capitalized word NOT at the start of a sentence
    const isMidSentenceCapital = /^[A-Z]/.test(word) && !/^[A-Z]/.test(input.trim());

    if (skip || isAllCaps || hasDigit || lower.length < 4) return word;
    if (isMidSentenceCapital) return word; // likely a proper noun (France, Lokesh, etc.)
    if (DICT_SET.has(lower) || ALLOW_LIST.has(lower)) return word;

    const suggestion = findSuggestion(lower);
    if (suggestion && suggestion !== lower) {
      // Only correct when edit distance is 1 (very confident) or word is longer
      const dist = levenshtein(lower, suggestion);
      if (dist > 1 && lower.length < 8) return word;
      const replacement = /^[A-Z]/.test(word)
        ? suggestion.charAt(0).toUpperCase() + suggestion.slice(1)
        : suggestion;
      corrections.push({ from: word, to: replacement });
      return replacement;
    }
    return word;
  });

  return {
    original: input,
    corrected,
    changed: corrections.length > 0,
    corrections,
  };
}
